# Generated by Django 5.2 on 2026-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='scit.uinsuka@gmail.com', max_length=254)),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain website')),
                ('github', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username github')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username instagram')),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profil linkedin')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact admin scit')),
                ('is_active', models.BooleanField(default=False, verbose_name="Aktifkan untuk menampilkanya saat get *[0]")),
            ],
        ),
    ]
