# Generated by Django 5.2 on 2025-09-27 03:38

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid6.uuid7)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('decriptions', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to='')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_modul', models.ManyToManyField(to='iot.feature')),
                ('user_modul', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('last_data', models.DateTimeField(auto_now=True)),
                ('data_feature_modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.feature')),
                ('data_modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot.modul')),
            ],
        ),
    ]
