# Generated by Django 5.2 on 2025-09-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modul',
            old_name='decriptions',
            new_name='descriptions',
        ),
    ]
