# Generated by Django 5.2 on 2025-09-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_rename_decriptions_modul_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='type',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
