# Generated by Django 5.2 on 2025-09-27 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_modul_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modul',
            old_name='uuid',
            new_name='serial_id',
        ),
    ]
