# Generated by Django 5.2 on 2025-09-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_rename_uuid_modul_serial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='pin',
            field=models.CharField(default='123456', max_length=10),
            preserve_default=False,
        ),
    ]
