# Generated by Django 5.2 on 2025-09-27 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_modul_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='modul',
            old_name='feature_modul',
            new_name='feature',
        ),
        migrations.RemoveField(
            model_name='modul',
            name='user_modul',
        ),
        migrations.AddField(
            model_name='modul',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
