# Generated by Django 5.2 on 2025-09-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_rename_feature_modul_modul_feature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='pin',
        ),
        migrations.AddField(
            model_name='modul',
            name='password',
            field=models.CharField(default='paktani', max_length=10),
        ),
    ]
