# Generated by Django 5.2 on 2025-10-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_remove_modul_pin_modul_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModul',
        ),
    ]
