# Generated by Django 5.2 on 2025-10-09 03:20

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_delete_datamodul'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='auth_id',
            field=models.UUIDField(default=uuid6.uuid7),
        ),
    ]
