# Generated by Django 5.2 on 2025-10-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_modul_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255, null=True)),
                ('last_data', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.feature')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='iot.modul')),
            ],
        ),
    ]
