# Generated by Django 5.2 on 2025-11-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0010_datamodul'),
        ('schedule', '0007_groupschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.IntegerField(default=0)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pins', to='schedule.groupschedule')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='iot.modul')),
            ],
        ),
    ]
