# Generated by Django 5.2 on 2025-11-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_modulepin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodul',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
