# Generated by Django 5.2 on 2025-11-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0012_alter_datamodul_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepin',
            name='descriptions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='modulepin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
