# Generated by Django 5.2 on 2025-11-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0013_modulepin_descriptions_modulepin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepin',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
