# Generated by Django 5.2 on 2026-01-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0014_modulepin_type'),
        ('schedule', '0010_groupschedule_sequential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='modul', max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_modul', to='iot.modul')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_group', to='schedule.groupschedule')),
            ],
        ),
    ]
