# Generated by Django 5.2 on 2026-01-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0015_modulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelog',
            name='alarm_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modulelog',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modulelog',
            name='type',
            field=models.CharField(blank=True, default='modul', max_length=50, null=True),
        ),
    ]
