# Generated by Django 5.2 on 2025-10-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0008_delete_datamodul'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Label atau nama untuk alaram', max_length=100)),
                ('time', models.TimeField(help_text='Waktu alaram akan berbunyi (HH:MM:SS)')),
                ('is_active', models.BooleanField(default=True, help_text='Status alaram aktif atau tidak')),
                ('repeat_monday', models.BooleanField(default=False)),
                ('repeat_tuesday', models.BooleanField(default=False)),
                ('repeat_wednesday', models.BooleanField(default=False)),
                ('repeat_thursday', models.BooleanField(default=False)),
                ('repeat_friday', models.BooleanField(default=False)),
                ('repeat_saturday', models.BooleanField(default=False)),
                ('repeat_sunday', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Pengguna pemilik alaram', on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='iot.modul')),
            ],
            options={
                'verbose_name': 'Alaram',
                'verbose_name_plural': 'Daftar Alaram',
                'ordering': ['time'],
            },
        ),
    ]
