# Generated by Django 5.2 on 2025-10-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarm',
            old_name='user',
            new_name='modul',
        ),
    ]
