# Generated by Django 5.2 on 2025-10-07 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_delete_datamodul'),
        ('schedule', '0002_rename_user_alarm_modul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='modul',
            field=models.ForeignKey(help_text='Modul pemilik alaram', on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='iot.modul'),
        ),
    ]
