# Generated by Django 5.2 on 2025-10-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_alarm_modul'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='celery_task_id',
            field=models.CharField(blank=True, editable=False, help_text='ID dari tugas Celery yang dijadwalkan di background', max_length=255, null=True),
        ),
    ]
