# Generated by Django 5.2 on 2025-10-11 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_modul_auth_id'),
        ('schedule', '0004_alarm_celery_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_log', to='iot.modul')),
            ],
        ),
    ]
