# Generated by Django 5.2 on 2025-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='duration',
            field=models.BigIntegerField(default=0, help_text='Waktu alaram akan menyala (detik)'),
        ),
    ]
