# Generated by Django 5.2 on 2025-11-07 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_modulepin'),
        ('schedule', '0007_groupschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='modul',
        ),
        migrations.RemoveField(
            model_name='groupschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='alarm',
            name='group',
            field=models.ForeignKey(default=None, help_text='Modul pemilik alaram', on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='schedule.groupschedule'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='modul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.modul'),
        ),
    ]
