# Generated by Django 5.2 on 2025-11-07 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0011_modulepin'),
        ('schedule', '0008_remove_alarm_modul_remove_groupschedule_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='modul',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iot.modul'),
            preserve_default=False,
        ),
    ]
