# Generated by Django 5.2 on 2025-11-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_groupschedule_modul'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupschedule',
            name='sequential',
            field=models.IntegerField(default=0),
        ),
    ]
